###### Site settings
title            : Inspect
metatitle        : Web Development and Tech Podcast
description      : Inspect is a weekly(ish) show about the world of web development, design and technology (plus other random bits) hosted by Ajay Karwal and Les McCutcheon.
tagline          : A weekly(ish) podcast about web development, design, technology and some other random stuff.
email            : inspectfm@gmail.com
base_url         : http://inspect.fm
encoding         : utf-8

google_analytics : UA-93339523-1

author:
  name           : Ajay Karwal
  email          : inspectfm@gmail.com

# Social accounts
twitter:
  inspect        : inspectfm
  ajay           : ajaykarwal
  les            : lesmac2

# Feeds and iTunes
feeds:
  itunes         : https://itunes.apple.com/gb/podcast/inspect/id1213377482
  pocket_casts   : http://pca.st/pmyU
  overcast       : https://overcast.fm/itunes1213377482/inspect
  stitcher       : http://www.stitcher.com/s?fid=133154&refid=stpr
  soundcloud     : http://soundcloud.com/inspectfm
  rss            : /feed.xml

itunes_artwork   : /images/inspectfm_artwork.png
audio_host       : http://dts.podtrac.com/redirect.mp3/s3.eu-west-2.amazonaws.com/inspectfm/episodes/

gems:
  - jekyll-sitemap
  - emoji_for_jekyll
  - jekyll-feed


# Add _pages directory to jekyll build
include: ["_pages"]

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md


# Build settings
permalink: /:title/
sass:
  style: compressed

future: false
