###### Site settings
title            : Inspect
metatitle        : Web Development and Tech Podcast
description      : A weekly(ish) podcast about web development, design, technology and some other random stuff.
tagline          : A weekly(ish) podcast about web development, design, technology and some other random stuff.
email            : inspectfm@gmail.com
base_url         : http://inspect.fm
encoding         : utf-8

google_analytics : UA-93339523-1

author:
  name           : Ajay Karwal
  email          : inspectfm@gmail.com

# Social accounts
twitter:
  inspect        : inspectfm
  ajay           : ajaykarwal
  les            : lesmac2

# Feed URLs
feeds:
  itunes       : https://itunes.apple.com/gb/podcast/inspect/id1213377482
  pocket_casts : http://pca.st/pezi
  stitcher     : http://www.stitcher.com/podcast/inspect?refid=stpr
  soundcloud   : http://soundcloud.com/inspectfm
  rss          : /feed.xml

# rss          : http://feeds.feedburner.com/inspectfm

aws_baseurl  : https://s3.eu-west-2.amazonaws.com/inspectfm/episodes/

gems:
  - jekyll-sitemap
  - emoji_for_jekyll
  - jekyll-feed


# Add _pages directory to jekyll build
include: ["_pages"]

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md


# Build settings
permalink: /:title/
sass:
  style: compressed

# Conversion
# markdown:    kramdown

# Markdown Processors
# kramdown:
#   input: GFM
#   auto_ids: true
#   syntax_highlighter: rouge
