###### Site settings
title            : Inspect
metatitle        : A Podcast about Design + Development
description      : Inspect is a show about the world of web development, design and technology hosted by Ajay Karwal — a designer and front-end developer from Buckingham, and Kay Mankoo — a full stack developer from London.
tagline          : A Podcast about Design + Development
email            : inspectfm@gmail.com
base_url         : https://inspectpodcast.com
encoding         : utf-8

google_analytics : UA-93339523-1

author:
  name           : Ajay Karwal
  email          : inspectfm@gmail.com

# Social accounts
twitter:
  inspect        : inspectpodcast
  ajay           : ajaykarwal

# Feeds and iTunes
feeds:
  itunes         : https://itunes.apple.com/gb/podcast/inspect/id1213377482
  google         : https://podcasts.google.com/?feed=aHR0cHM6Ly9pbnNwZWN0LmZtL2ZlZWQueG1s
  pocket_casts   : https://pca.st/pmyU
  overcast       : https://overcast.fm/itunes1213377482/inspect
  stitcher       : https://www.stitcher.com/podcast/inspect
  castro         : https://castro.fm/podcast/6b146eb3-3415-4d66-8b6c-f22a908bd8d2
  soundcloud     : https://soundcloud.com/inspectfm
  youtube        : https://www.youtube.com/channel/UCdOFzk8F8-yCyH26Msq2kSA
  spotify        : https://open.spotify.com/show/0o5Q8dFP6MunHQEVKfvBgt?si=RbWyrw7QSYOr7-qJv3k7Xg
  facebook       : https://fb.me/inspectfm
  whatpods       : https://whatpods.com/podcasts/inspect/
  rss            : /feed.xml

feed_artwork     : /images/feed_artwork.jpg
feed_icon        : /images/feed_icon.svg
feed_logo        : /images/feed_logo.svg
# audio_host       : https://dts.podtrac.com/redirect.mp3/s3.eu-west-2.amazonaws.com/inspectfm/episodes/
audio_host       : https://media.blubrry.com/inspect/inspectfm.s3.eu-west-2.amazonaws.com/episodes/

plugins:
  - jekyll-sitemap
  - emoji_for_jekyll
  - jekyll-feed


# Add _pages directory to jekyll build
include: ["_pages"]

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor


# Build settings
permalink: /:title/
sass:
  style: compressed

future: false
