###### Site settings
title             : Inspect
metatitle         : Web Development & Tech Podcast
description       : Web Development & Tech Podcast
email             : inspectfm@gmail.com
url               : http://inspect.fm
encoding          : utf-8

google_analytics  : UA-93339523-1

# Social accounts
twitter_username  : inspectfm

# Feed URLs
rss          : http://feeds.feedburner.com/inspectfm
itunes       : https://itunes.apple.com/gb/podcast/inspect/id1213377482
pocket_casts : http://pca.st/pezi
stitcher     : http://www.stitcher.com/podcast/inspect?refid=stpr
soundcloud   : http://soundcloud.com/inspectfm
# rss          : http://feeds.soundcloud.com/users/soundcloud:users:290211107/sounds.rss
      

gems:
  - jekyll-sitemap
  - emoji_for_jekyll
  - jekyll-feed


# Add _pages directory to jekyll build
include: ["_pages"]

exclude:
 - Gemfile
 - Gemfile.lock
 - README.md

# Build settings
permalink: /:title/
sass:
  style: compressed

# Conversion
markdown:    kramdown

# Markdown Processors
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
