###### Site settings
title            : Inspect
metatitle        : A Podcast about Design + Development
description      : Inspect is a show about the world of web development, design and technology hosted by Ajay Karwal — a designer and front-end developer from Buckingham, and Kay Mankoo — a full stack developer from London.
tagline          : A Podcast about Design + Development
email            : inspectfm@gmail.com
base_url         : https://inspect.fm
encoding         : utf-8

google_analytics : UA-93339523-1

author:
  name           : Ajay Karwal
  email          : inspectfm@gmail.com

# Social accounts
twitter:
  inspect        : inspectfm
  ajay           : ajaykarwal

# Feeds and iTunes
feeds:
  itunes         : https://itunes.apple.com/gb/podcast/inspect/id1213377482
  pocket_casts   : https://pca.st/pmyU
  overcast       : https://overcast.fm/itunes1213377482/inspect
  stitcher       : https://www.stitcher.com/podcast/inspect
  castro         : https://castro.fm/podcast/6b146eb3-3415-4d66-8b6c-f22a908bd8d2
  soundcloud     : https://soundcloud.com/inspectfm
  rss            : /feed.xml

feed_artwork     : /images/feed_artwork.jpg
# audio_host       : https://dts.podtrac.com/redirect.mp3/s3.eu-west-2.amazonaws.com/inspectfm/episodes/
audio_host       : https://media.blubrry.com/inspect/inspectfm.s3.eu-west-2.amazonaws.com/episodes/

gems:
  - jekyll-sitemap
  - emoji_for_jekyll
  - jekyll-feed


# Add _pages directory to jekyll build
include: ["_pages"]

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md


# Build settings
permalink: /:title/
sass:
  style: compressed

future: false
